---
# tasks file for Debian
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - gnupg

- name: Add gpg key and repository
  block:
    - name: Create directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add gpg
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc

    - name: Add repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

- name: Install docker
  ansible.builtin.apt:
    pkg: "{{ packages }}"